fix: rake graphql:schema:dump
- undefined method `to_a' for an instance of String (NoMethodError)
- added csv gem which will be removed in ruby 3.4

SVA-1125